// examples/remix/app/routes/signup.tsx
import { auth } from "@auth/lucia.server";
import { LuciaError } from "lucia";
import { Form, useActionData } from "@remix-run/react";
import { redirect, json } from "@remix-run/node";
import { Prisma } from "@prisma/client";

import type { LoaderArgs, ActionArgs } from "@remix-run/node";

export default () => {
	const actionResult = useActionData<typeof action>();
	return (
		<>
			<h2>Create an account</h2>
			<a href="/api/oauth?provider=github" className="button">
				Continue with Github
			</a>
			<p className="center">or</p>
			<Form method="post">
				<label htmlFor="username">username</label>
				<br />
				<input id="username" name="username" />
				<br />
				<label htmlFor="password">password</label>
				<br />
				<input type="password" id="password" name="password" />
				<br />
				<input type="submit" value="Continue" className="button" />
			</Form>
			<p className="error">{actionResult?.error}</p>
			<a href="/login" className="link">
				Sign in
			</a>
		</>
	);
};

export const loader = async ({ request }: LoaderArgs) => {
	const headers = new Headers();
	const authRequest = auth.handleRequest(request, headers);
	const session = await authRequest.validate();
	if (session) return redirect("/");
	return json(null, {
		headers
	});
};

export const action = async ({ request }: ActionArgs) => {
	const formData = await request.formData();
	const username = formData.get("username");
	const password = formData.get("password");
	if (
		!username ||
		!password ||
		typeof username !== "string" ||
		typeof password !== "string"
	) {
		return json(
			{
				error: "Invalid input"
			},
			{
				status: 400
			}
		);
	}
	const headers = new Headers();
	try {
		const user = await auth.createUser({
			key: {
				providerId: "username",
				providerUserId: username,
				password
			},
			attributes: {
				username
			}
		});
		const session = await auth.createSession(user.userId, {
			attributes: {
				created_at: new Date()
			}
		});
		const authRequest = auth.handleRequest(request, headers);
		authRequest.setSession(session);
		return redirect("/", {
			headers
		});
	} catch (error) {
		if (
			error instanceof Prisma.PrismaClientKnownRequestError &&
			error.code === "P2002" &&
			error.message?.includes("username")
		) {
			return json(
				{
					error: "Username already in use"
				},
				{
					status: 400,
					headers
				}
			);
		}
		if (
			error instanceof LuciaError &&
			error.message === "AUTH_DUPLICATE_KEY_ID"
		) {
			return json(
				{
					error: "Username already in use"
				},
				{
					status: 400,
					headers
				}
			);
		}
		// database connection error
		console.log(error);
		return json(
			{
				error: "Unknown error occurred"
			},
			{
				status: 500,
				headers
			}
		);
	}
};

// examples/solidstart/username-and-password/src/routes/signup.tsx
import { Show } from "solid-js";
import { auth } from "../auth/lucia";
import { A } from "solid-start";
import { ServerError } from "solid-start/server";
import { SqliteError } from "better-sqlite3";

import {
	createServerAction$,
	createServerData$,
	redirect
} from "solid-start/server";

export const routeData = () => {
	return createServerData$(async (_, event) => {
		const authRequest = auth.handleRequest(event.request);
		const session = await authRequest.validate();
		if (session) {
			return redirect("/");
		}
	});
};

const Page = () => {
	const [enrolling, { Form }] = createServerAction$(
		async (formData: FormData) => {
			const username = formData.get("username");
			const password = formData.get("password");
			if (
				typeof username !== "string" ||
				username.length < 4 ||
				username.length > 31
			) {
				throw new ServerError("Invalid username");
			}
			if (
				typeof password !== "string" ||
				password.length < 6 ||
				password.length > 255
			) {
				throw new ServerError("Invalid password");
			}
			try {
				const user = await auth.createUser({
					key: {
						providerId: "username", // auth method
						providerUserId: username.toLowerCase(), // unique id when using "username" auth method
						password // hashed by Lucia
					},
					attributes: {
						username
					}
				});
				const session = await auth.createSession({
					userId: user.userId,
					attributes: {}
				});
				const sessionCookie = auth.createSessionCookie(session);
				// set cookie and redirect
				return new Response(null, {
					status: 302,
					headers: {
						Location: "/",
						"Set-Cookie": sessionCookie.serialize()
					}
				});
			} catch (e) {
				// check for unique constraint error in user table
				if (e instanceof SqliteError && e.code === "SQLITE_CONSTRAINT_UNIQUE") {
					throw new ServerError("Username already taken");
				}
				throw new ServerError("An unknown error occurred", {
					status: 500
				});
			}
		}
	);
	return (
		<>
			<h1>Sign up</h1>
			<Form>
				<label for="username">Username</label>
				<input name="username" id="username" />
				<br />
				<label for="password">Password</label>
				<input type="password" name="password" id="password" />
				<br />
				<input type="submit" />
			</Form>
			<Show when={enrolling.error}>
				<p class="error">{enrolling.error.message}</p>;
			</Show>
			<A href="/login">Sign in</A>
		</>
	);
};

export default Page;
