// examples/nuxt/pages/index.vue
<script lang="ts" setup>
const { data } = await useFetch("/api/user");
if (!data.value) throw createError("Failed to fetch data");
const session = data.value.session;
if (!session) await navigateTo("/login");

const handleSubmit = async (e: Event) => {
	if (!(e.target instanceof HTMLFormElement)) return;
	try {
		const data = await $fetch("/api/logout", {
			method: "POST"
		});
		if (data) {
			return;
		}
		navigateTo("/login");
	} catch (error) {}
};
</script>
<template>
	<p>This page is protected and can only be accessed by authenticated users.</p>
	<pre class="code">{{ JSON.stringify(session, null, 2) }}</pre>

	<form @submit.prevent="handleSubmit">
		<input type="submit" class="button" value="Sign out" />
	</form>
</template>

// examples/nextjs/pages/index.tsx
import { useRouter } from "next/router";
import { auth } from "../auth/lucia";

import type {
	GetServerSidePropsContext,
	GetServerSidePropsResult,
	InferGetServerSidePropsType
} from "next";
import type { Session } from "lucia";

export const getServerSideProps = async (
	context: GetServerSidePropsContext
): Promise<GetServerSidePropsResult<{ session: Session }>> => {
	const authRequest = auth.handleRequest(context);
	const session = await authRequest.validate();
	if (!session)
		return {
			redirect: {
				destination: "/login",
				permanent: false
			}
		};
	return {
		props: {
			session
		}
	};
};

const Index = (
	props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
	const router = useRouter();
	return (
		<>
			<p>
				This page is protected and can only be accessed by authenticated users.
			</p>
			<pre className="code">{JSON.stringify(props.session, null, 2)}</pre>

			<button
				onClick={async () => {
					try {
						await fetch("/api/logout", {
							method: "POST"
						});
						router.push("/login");
					} catch (e) {
						console.log(e);
					}
				}}
			>
				Sign out
			</button>
		</>
	);
};

export default Index;
