// examples/nuxt/email-and-password/pages/email-verification.vue
<script lang="ts" setup>
definePageMeta({
	middleware: ["protected"]
});

const user = useAuthenticatedUser();

if (user.value.emailVerified) {
	await navigateTo("/");
}

const successMessage = ref<null | string>(null);

const handleResend = async (e: Event) => {
	if (!(e.target instanceof HTMLFormElement)) return;
	successMessage.value = null;
	await $fetch("/api/email-verification", {
		method: "POST",
		redirect: "manual"
	});
	successMessage.value = "Your verification link was resent";
};
</script>

<template>
	<h1>Email verification</h1>
	<p>Your email verification link was sent to your inbox (i.e. console).</p>
	<h2>Resend verification link</h2>
	<form
		method="post"
		action="/api/email-verification"
		@submit.prevent="handleResend"
	>
		<input type="submit" value="Resend" />
	</form>
	<p v-if="successMessage">{successMessage}</p>
</template>

// examples/sveltekit/email-and-password/src/routes/email-verification/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';

	import type { ActionData } from './$types';

	export let form: ActionData;
</script>

<h1>Email verification</h1>
<p>Your email verification link was sent to your inbox (i.e. console).</p>
<h2>Resend verification link</h2>
<form method="post" use:enhance>
	<input type="submit" value="Resend" />
</form>
{#if form?.success}
	<p>Your verification link was resent</p>
{/if}
