// examples/nuxt/email-and-password/pages/password-reset/[token].vue
<script lang="ts" setup>
const errorMessage = ref<string | null>(null);

const handleSubmit = async (e: Event) => {
	if (!(e.target instanceof HTMLFormElement)) return;
	errorMessage.value = null;
	const formData = new FormData(e.target);
	try {
		await $fetch(e.target.action, {
			method: "POST",
			body: {
				password: formData.get("password")
			},
			redirect: "manual"
		});
		await navigateTo("/");
	} catch (e) {
		const { data: error } = e as {
			data: {
				message: string;
			};
		};
		errorMessage.value = error.message;
	}
};

const route = useRoute();
const apiRoute = `/api/password-reset/${route.params.token}`;
</script>

<template>
	<h1>Reset password</h1>
	<form method="post" :action="apiRoute" @submit.prevent="handleSubmit">
		<label htmlFor="password">New Password</label>
		<input name="password" id="password" />
		<br />
		<input type="submit" />
	</form>
	<p class="error" v-if="errorMessage">{{ errorMessage }}</p>
</template>

// examples/nextjs-pages/email-and-password/pages/password-reset/[token].tsx
import { useRouter } from "next/router";
import { isValidPasswordResetToken } from "@/auth/verification-token";
import { useState } from "react";

import type {
	GetServerSidePropsContext,
	GetServerSidePropsResult,
	InferGetServerSidePropsType
} from "next";

export const getServerSideProps = async (
	context: GetServerSidePropsContext<{
		token: string;
	}>
): Promise<GetServerSidePropsResult<{
	token: string
}>> => {
	const token = context.params?.token as string;
	const validToken = await isValidPasswordResetToken(token);
	if (!validToken) {
		return {
			redirect: {
				destination: "/password-reset",
				permanent: false
			}
		};
	}
	return {
		props: {
			token
		}
	};
};

const Page = (
	props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
	const router = useRouter();
	const [errorMessage, setErrorMessage] = useState<string | null>(null);
	return (
		<>
			<h1>Sign in</h1>
			<form
				method="post"
				action={`/api/password-reset/${props.token}`}
				onSubmit={async (e) => {
					e.preventDefault();
					setErrorMessage(null);
					const formData = new FormData(e.currentTarget);
					const response = await fetch(`/api/password-reset/${props.token}`, {
						method: "POST",
						body: JSON.stringify({
							password: formData.get("password")
						}),
						headers: {
							"Content-Type": "application/json"
						},
						redirect: "manual"
					});

					if (response.ok || response.status === 0) {
						router.push("/"); // redirect to profile page on success
					} else {
						const result = (await response.json()) as {
							error?: string;
						};
						setErrorMessage(result?.error ?? null);
					}
				}}
			>
				<label htmlFor="password">New Password</label>
				<input name="password" id="password" />
				<br />
				<input type="submit" />
			</form>
			{errorMessage && <p className="error">{errorMessage}</p>}
		</>
	);
};

export default Page;
