// examples/nuxt/email-and-password/pages/password-reset/index.vue
<script lang="ts" setup>
const errorMessage = ref<string | null>(null);
const successMessage = ref<string | null>(null);

const handleSubmit = async (e: Event) => {
	if (!(e.target instanceof HTMLFormElement)) return;
	errorMessage.value = null;
	successMessage.value = null;
	const formData = new FormData(e.target);
	try {
		await $fetch(e.target.action, {
			method: "POST",
			body: {
				email: formData.get("email")
			},
			redirect: "manual"
		});
		successMessage.value = "Your password reset link was sent to your inbox";
	} catch (e) {
		const { data: error } = e as {
			data: {
				message: string;
			};
		};
		errorMessage.value = error.message;
	}
};
</script>

<template>
	<h1>Reset password</h1>
	<form
		method="post"
		action="/api/password-reset"
		@submit.prevent="handleSubmit"
	>
		<label for="email">Email</label>
		<input name="email" id="email" /><br />
		<input type="submit" />
	</form>
	<p class="error" v-if="errorMessage">{{ errorMessage }}</p>
	<p v-if="successMessage">{{ successMessage }}</p>
	<NuxtLink to="/login">Sign in</NuxtLink>
</template>

// examples/nextjs-pages/email-and-password/pages/password-reset/index.tsx
import { useState } from "react";

import Link from "next/link";

const Page = () => {
	const [errorMessage, setErrorMessage] = useState<string | null>(null);
	const [successMessage, setSuccessMessage] = useState<string | null>(null);
	return (
		<>
			<h1>Reset password</h1>
			<form
				method="post"
				action="/api/password-reset"
				onSubmit={async (e) => {
					e.preventDefault();
					setErrorMessage(null);
					setSuccessMessage(null);
					const formData = new FormData(e.currentTarget);
					const response = await fetch("/api/password-reset", {
						method: "POST",
						body: JSON.stringify({
							email: formData.get("email")
						}),
						headers: {
							"Content-Type": "application/json"
						}
					});
					if (!response.ok) {
						const result = (await response.json()) as {
							error?: string;
						};
						setErrorMessage(result?.error ?? null);
						return;
					}
					setSuccessMessage("Your password reset link was sent to your inbox");
				}}
			>
				<label htmlFor="email">Email</label>
				<input name="email" id="email" />
				<br />
				<input type="submit" />
			</form>
			{successMessage && <p>{successMessage}</p>}
			{errorMessage && <p className="error">{errorMessage}</p>}
			<Link href="/login">Sign in</Link>
		</>
	);
};

export default Page;
