// test-apps/nuxt/pages/index.vue
<script lang="ts" setup>
const { data, error } = await useFetch("/api/user");
if (error.value) throw createError(error.value.message);
if (!data.value?.user) navigateTo("/login");

const handleSubmit = async (e: Event) => {
	if (!(e.target instanceof HTMLFormElement)) return;
	try {
		await $fetch("/api/logout", { method: "POST" });
		navigateTo("/login");
	} catch (error) {
		console.error(error);
	}
};
</script>
<template>
	<p>This page is protected and can only be accessed by authenticated users.</p>
	<pre class="code">{{ JSON.stringify(data?.user, null, 2) }}</pre>
	<form @submit.prevent="handleSubmit">
		<input type="submit" class="button" value="Sign out" />
	</form>
	<NuxtLink to="/middleware" class="button">Middleware</NuxtLink>
</template>

// test-apps/nextjs/pages/index.tsx
import { useRouter } from "next/router";
import { auth } from "../auth/lucia";

import type {
	GetServerSidePropsContext,
	GetServerSidePropsResult,
	InferGetServerSidePropsType,
} from "next";
import type { User } from "lucia-auth";

export const getServerSideProps = async (
	context: GetServerSidePropsContext
): Promise<GetServerSidePropsResult<{ user: User }>> => {
	const authRequest = auth.handleRequest(context);
	const { user } = await authRequest.validateUser();
	if (!user)
		return {
			redirect: {
				destination: "/login",
				permanent: false
			}
		};
	return {
		props: {
			user
		}
	};
};

const Index = (
	props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
	const router = useRouter();
	return (
		<>
			<p>
				This page is protected and can only be accessed by authenticated users.
			</p>
			<pre className="code">{JSON.stringify(props.user, null, 2)}</pre>

			<button
				onClick={async () => {
					try {
						await fetch("/api/logout", {
							method: "POST"
						});
						router.push("/login");
					} catch (e) {
						console.log(e);
					}
				}}
			>
				Sign out
			</button>
		</>
	);
};

export default Index;
