// examples/solidstart/username-and-password/src/routes/signup.tsx
import { Show } from "solid-js";
import { auth } from "../auth/lucia";
import { A } from "solid-start";
import { ServerError } from "solid-start/server";
import { SqliteError } from "better-sqlite3";

import {
	createServerAction$,
	createServerData$,
	redirect
} from "solid-start/server";

export const routeData = () => {
	return createServerData$(async (_, event) => {
		const authRequest = auth.handleRequest(event.request);
		const session = await authRequest.validate();
		if (session) {
			return redirect("/");
		}
	});
};

const Page = () => {
	const [enrolling, { Form }] = createServerAction$(
		async (formData: FormData) => {
			const username = formData.get("username");
			const password = formData.get("password");
			if (
				typeof username !== "string" ||
				username.length < 4 ||
				username.length > 31
			) {
				throw new ServerError("Invalid username");
			}
			if (
				typeof password !== "string" ||
				password.length < 6 ||
				password.length > 255
			) {
				throw new ServerError("Invalid password");
			}
			try {
				const user = await auth.createUser({
					key: {
						providerId: "username", // auth method
						providerUserId: username.toLowerCase(), // unique id when using "username" auth method
						password // hashed by Lucia
					},
					attributes: {
						username
					}
				});
				const session = await auth.createSession({
					userId: user.userId,
					attributes: {}
				});
				const sessionCookie = auth.createSessionCookie(session);
				// set cookie and redirect
				return new Response(null, {
					status: 302,
					headers: {
						Location: "/",
						"Set-Cookie": sessionCookie.serialize()
					}
				});
			} catch (e) {
				// check for unique constraint error in user table
				if (e instanceof SqliteError && e.code === "SQLITE_CONSTRAINT_UNIQUE") {
					throw new ServerError("Username already taken");
				}
				throw new ServerError("An unknown error occurred", {
					status: 500
				});
			}
		}
	);
	return (
		<>
			<h1>Sign up</h1>
			<Form>
				<label for="username">Username</label>
				<input name="username" id="username" />
				<br />
				<label for="password">Password</label>
				<input type="password" name="password" id="password" />
				<br />
				<input type="submit" />
			</Form>
			<Show when={enrolling.error}>
				<p class="error">{enrolling.error.message}</p>;
			</Show>
			<A href="/login">Sign in</A>
		</>
	);
};

export default Page;

// examples/qwik/username-and-password/src/routes/(auth)/signup/index.tsx
import { component$ } from "@builder.io/qwik";
import { Form, Link, routeAction$, zod$ } from "@builder.io/qwik-city";
import { SqliteError } from "better-sqlite3";

import { auth } from "~/auth/lucia";

export const useSignUpAction = routeAction$(
	async (data, event) => {
		try {
			const { username, password } = data;
			const user = await auth.createUser({
				key: {
					providerId: "username",
					providerUserId: username.toLowerCase(),
					password
				},
				attributes: {
					username
				}
			});
			const session = await auth.createSession({
				userId: user.userId,
				attributes: {}
			});
			const { name, value, attributes } = auth.createSessionCookie(session);
			event.cookie.set(name, value, attributes);
			throw event.redirect(302, "/");
		} catch (e) {
			if (e instanceof SqliteError && e.code === "SQLITE_CONSTRAINT_UNIQUE") {
				return {
					success: false,
					error: "Unable to create user"
				};
			}
		}
	},
	zod$((z) => {
		return z
			.object({
				username: z.string().min(4).max(31),
				password: z.string().min(6).max(255),
				confirmPassword: z.string().optional()
			})
			.superRefine(({ password, confirmPassword }, ctx) => {
				if (confirmPassword !== password) {
					ctx.addIssue({
						code: "custom",
						message: "The passwords did not match",
						path: ["password"]
					});
				}
			});
	})
);

export default component$(() => {
	const signUpAction = useSignUpAction();
	return (
		<>
			<h1>Sign up</h1>
			<Form action={signUpAction}>
				<label for="username">Username</label>
				<input name="username" id="username" />
				<br />
				<label for="password">Password</label>
				<input type="password" name="password" id="password" />
				<br />
				<label for="confirmPassword">Confirm Password</label>
				<input type="password" name="confirmPassword" id="password" />
				<br />
				<input type="submit" />
			</Form>
			{signUpAction.value?.fieldErrors?.username?.length && (
				<>
					<h3>Username Issue(s):</h3>
					{signUpAction.value.fieldErrors.username.map((error, index) => (
						<p key={index} class="error">
							{error}
						</p>
					))}
				</>
			)}
			{signUpAction.value?.fieldErrors?.password?.length && (
				<>
					<h3>Password Issue(s):</h3>
					{signUpAction.value.fieldErrors.password.map((error, index) => (
						<p key={index} class="error">
							{error}
						</p>
					))}
				</>
			)}
			{signUpAction.value?.error && (
				<p class="error">{signUpAction.value.error}</p>
			)}
			<Link href="/signin">Sign in</Link>
		</>
	);
});
