// examples/nextjs/pages/profile.tsx
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { AuthRequest } from "@lucia-auth/nextjs";
import { auth } from "../lib/lucia";
import { getUser, signOut } from "@lucia-auth/nextjs/client";

import type {
	GetServerSidePropsContext,
	GetServerSidePropsResult,
	InferGetServerSidePropsType
} from "next";
import type { User } from "lucia-auth";

export const getServerSideProps = async (
	context: GetServerSidePropsContext
): Promise<GetServerSidePropsResult<{ user: User; notes: string }>> => {
	const authRequest = new AuthRequest(auth, context.req, context.res);
	const { user } = await authRequest.getSessionUser();
	if (!user)
		return {
			redirect: {
				destination: "/login",
				permanent: false
			}
		};
	const notes = context.req.cookies.notes || "";
	return {
		props: {
			user,
			notes
		}
	};
};

const Index = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => {
	const router = useRouter();
	const [randomNumber, setRandomNumber] = useState<null | number>(null);
	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		const formValues = e.target as any as Record<
			"notes",
			{
				value: string;
			}
		>;
		await fetch("/api/notes", {
			method: "POST",
			body: JSON.stringify({
				notes: formValues.notes.value
			})
		});
	};
	const updateRandomNumber = async () => {
		const response = await fetch("/api/random-number");
		if (!response.ok) throw new Error();
		const result = (await response.json()) as {
			number: number;
		};
		setRandomNumber(result.number);
	};
	const getUserWithRequest = async () => {
		console.log(await getUser());
	};
	useEffect(() => {
		updateRandomNumber();
		getUserWithRequest();
	}, []);
	return (
		<>
			<h1>Profile</h1>
			<p>This page is protected and can only be accessed by authenticated users.</p>
			<div>
				<p>User id: {props.user?.userId}</p>
				<p>Username: {props.user?.username}</p>
				<p>Random number API: {randomNumber ?? "loading..."}</p>
			</div>

			<div>
				<h2>Notes</h2>
				<form method="post" onSubmit={handleSubmit}>
					<input defaultValue={props.notes} name="notes" />
					<input type="submit" value="Save" className="button" />
				</form>
			</div>

			<button
				onClick={async () => {
					try {
						await signOut();
						router.push("/login");
					} catch (e) {
						console.log(e);
					}
				}}
			>
				Sign out
			</button>
		</>
	);
};

export default Index;

// apps/example-username-password/src/routes/profile/+page.svelte
<script lang="ts">
	import { signOut, getSession } from 'lucia-sveltekit/client';

	const lucia = getSession();
	const signOutUser = async () => {
		await signOut($lucia?.access_token || '');
		window.location.href = '/';
	};

	let number = 0;

	const fetchNumber = async () => {
		const response = await fetch('/api/random-number', {
			headers: {
				Authorization: `Bearer ${$lucia?.access_token}`
			}
		});
		const result = await response.json();
		if (result.error) {
			console.error(result.error);
			return;
		}
		number = result.number;
	};
</script>

<h2>Profile</h2>
<p>This page is protected and can only be accessed by authenticated users.</p>
<div>
	<p>user id: {$lucia?.user.user_id}</p>
	<p>username: {$lucia?.user.username}</p>
</div>

<div>
	<form on:submit|preventDefault={fetchNumber} action="/api/random-number" method="get">
		<input type="submit" value="Get random number" class="button" />
	</form>
	<p>result: {number}</p>
</div>

<button on:click={signOutUser}>Sign out</button>
