// examples/nextjs-app/email-and-password/app/password-reset/[token]/page.tsx
import Form from "@/components/form";

const Page = async ({params}: {
    params: {
        token: string
    }
}) => {
	return (
		<>
			<h1>Reset password</h1>
			<Form action={`/api/password-reset/${params.token}`} successRedirect="/">
				<label htmlFor="password">New Password</label>
				<input name="password" id="password" />
				<br />
				<input type="submit" />
			</Form>
		</>
	);
};

export default Page;

// examples/sveltekit/email-and-password/src/routes/password-reset/[token]/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';

	import type { ActionData } from './$types';

	export let form: ActionData;
</script>

<h1>Reset password</h1>
<form method="post" use:enhance>
	<label for="password">New Password</label>
	<input name="password" id="password" /><br />
	<input type="submit" />
</form>
{#if form?.message}
	<p class="error">{form.message}</p>
{/if}
