// examples/nuxt/username-and-password/pages/login.vue
<script lang="ts" setup>
const user = useUser();
if (user.value) {
	await navigateTo("/"); // redirect to profile page
}

const errorMessage = ref<string | null>(null);

const handleSubmit = async (e: Event) => {
	if (!(e.target instanceof HTMLFormElement)) return;
	const formData = new FormData(e.target);
	try {
		await $fetch("/api/login", {
			method: "POST",
			body: {
				username: formData.get("username"),
				password: formData.get("password")
			},
			redirect: "manual"
		});
		await navigateTo("/"); // profile page
	} catch (e) {
		const { data: error } = e as {
			data: {
				message: string;
			};
		};
		errorMessage.value = error.message;
	}
};
</script>

<template>
	<h1>Sign in</h1>
	<form method="post" action="/api/login" @submit.prevent="handleSubmit">
		<label for="username">Username</label>
		<input name="username" id="username" /><br />
		<label for="password">Password</label>
		<input type="password" name="password" id="password" /><br />
		<input type="submit" />
	</form>
	<p class="error">{{ errorMessage }}</p>
	<NuxtLink to="/signup">Create an account</NuxtLink>
</template>

// test-apps/username-password/src/routes/login/+page.svelte
<script lang="ts">
	export let errors: { message: string}
	let username: string, password: string;

	const login = async (e:SubmitEvent) => {
        const form = e.target as HTMLFormElement
		form.submit()
	};
</script>

<div>
	<h2>Sign in</h2>
	<form on:submit|preventDefault={login} action="/login" method="post">
		<label for="username">username</label><br />
		<input id="username" name="username" bind:value={username} /><br />
		<label for="password">password</label><br />
		<input type="password" id="password" name="password" bind:value={password} /><br />
        <input type="submit" value="Continue" class="button"/>
	</form>
	<p class="error">{errors?.message || ""}</p>
	<a href="/signup" class="link">Create a new account</a>
</div>
