// examples/nuxt/email-and-password/pages/password-reset/[token].vue
<script lang="ts" setup>
const errorMessage = ref<string | null>(null);

const handleSubmit = async (e: Event) => {
	if (!(e.target instanceof HTMLFormElement)) return;
	errorMessage.value = null;
	const formData = new FormData(e.target);
	try {
		await $fetch(e.target.action, {
			method: "POST",
			body: {
				password: formData.get("password")
			},
			redirect: "manual"
		});
		await navigateTo("/");
	} catch (e) {
		const { data: error } = e as {
			data: {
				message: string;
			};
		};
		errorMessage.value = error.message;
	}
};

const route = useRoute();
const apiRoute = `/api/password-reset/${route.params.token}`;
</script>

<template>
	<h1>Reset password</h1>
	<form method="post" :action="apiRoute" @submit.prevent="handleSubmit">
		<label htmlFor="password">New Password</label>
		<input name="password" id="password" />
		<br />
		<input type="submit" />
	</form>
	<p class="error" v-if="errorMessage">{{ errorMessage }}</p>
</template>

// examples/sveltekit-email/src/routes/password-reset/[token]/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { ActionData } from './$types';

	export let form: ActionData;
</script>

<h1>Reset password</h1>
<form method="post" use:enhance>
	<label for="new-password">New password</label>
	<input id="new-password" name="new-password" />
	<input type="submit" value="Reset password" class="button" />
</form>
{#if form?.message}
	<p class="error">{form.message}</p>
{/if}
