// examples/qwik/username-and-password/src/routes/index.tsx
import { component$ } from "@builder.io/qwik";
import {
	type DocumentHead,
	Form,
	routeAction$,
	routeLoader$
} from "@builder.io/qwik-city";

import { auth } from "~/auth/lucia";

export const useSessionUser = routeLoader$(async (event) => {
	const authRequest = auth.handleRequest(event);
	const session = await authRequest.validate();
	if (!session) throw event.redirect(302, "/signin/");
	return session.user;
});

export const useSignOutAction = routeAction$(async (_, event) => {
	const authRequest = auth.handleRequest(event);
	const session = await authRequest.validate();
	if (!session) throw event.error(401, "Unauthorized");

	await auth.invalidateSession(session.sessionId);
	const { name, value, attributes } = auth.createSessionCookie(null);
	event.cookie.set(name, value, attributes);
	throw event.redirect(302, "/login/");
});

export default component$(() => {
	const user = useSessionUser();
	const signout = useSignOutAction();
	return (
		<>
			<h1>Profile</h1>
			<p>User id: {user.value.userId}</p>
			<p>Username: {user.value.username}</p>
			<Form action={signout}>
				<button>Sign out</button>
			</Form>
		</>
	);
});

export const head: DocumentHead = {
	title: "GitHub OAuth with Lucia",
	meta: [
		{
			name: "description",
			content: "Qwik site description"
		}
	]
};

// examples/solidstart/github-oauth/src/routes/index.tsx
import { useRouteData } from "solid-start";
import {
	ServerError,
	createServerAction$,
	createServerData$,
	redirect
} from "solid-start/server";
import { auth } from "~/auth/lucia";

export const routeData = () => {
	return createServerData$(async (_, event) => {
		const authRequest = auth.handleRequest(event.request);
		const session = await authRequest.validate();
		if (!session) {
			return redirect("/login") as never;
		}
		return session.user;
	});
};

const Page = () => {
	const user = useRouteData<typeof routeData>();
	const [_, { Form }] = createServerAction$(async (_, event) => {
		const authRequest = auth.handleRequest(event.request);
		const session = await authRequest.validate();
		if (!session) {
			throw new ServerError("Unauthorized", {
				status: 401
			});
		}
		await auth.invalidateSession(session.sessionId); // invalidate session
		const sessionCookie = auth.createSessionCookie(null);
		return new Response(null, {
			status: 302,
			headers: {
				Location: "/login",
				"Set-Cookie": sessionCookie.serialize()
			}
		});
	});
	return (
		<>
			<h1>Profile</h1>
			<p>User id: {user()?.userId}</p>
			<p>Github username: {user()?.githubUsername}</p>
			<Form>
				<button>Sign out</button>
			</Form>
		</>
	);
};

export default Page;
