// test-apps/remix/app/root.tsx
import type { LinksFunction, V2_MetaFunction } from "@remix-run/node";

import {
	Links,
	LiveReload,
	Meta,
	Outlet,
	Scripts,
	ScrollRestoration
} from "@remix-run/react";

import styles from "./root.css";

export const links: LinksFunction = () => [
	{
		rel: "stylesheet",
		href: styles
	}
];

export const meta: V2_MetaFunction = () => [{ title: "Lucia + Remix demo" }];

export default function App() {
	return (
		<html lang="en">
			<head>
				<meta charSet="utf-8" />
				<meta name="viewport" content="width=device-width,initial-scale=1" />
				<Meta />
				<Links />
			</head>
			<body>
				<h1>
					<a href="/">Lucia + Remix demo</a>
				</h1>
				<Outlet />
				<ScrollRestoration />
				<Scripts />
				<LiveReload />
			</body>
		</html>
	);
}

// examples/solidstart/username-and-password/src/root.tsx
// @refresh reload
import { Suspense } from "solid-js";
import {
	Body,
	ErrorBoundary,
	FileRoutes,
	Head,
	Html,
	Meta,
	Routes,
	Scripts,
	Title
} from "solid-start";
import "./root.css";

export default function Root() {
	return (
		<Html lang="en">
			<Head>
				<Title>Username and password auth with Lucia</Title>
				<Meta charset="utf-8" />
				<Meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Body>
				<Suspense>
					<ErrorBoundary>
						<Routes>
							<FileRoutes />
						</Routes>
					</ErrorBoundary>
				</Suspense>
				<Scripts />
			</Body>
		</Html>
	);
}
