// examples/nextjs-app/username-and-password/app/login/page.tsx
import { getPageSession } from "@/auth/lucia";
import { redirect } from "next/navigation";

import Form from "@/components/form";
import Link from "next/link";

const Page = async () => {
	const session = await getPageSession();
	if (session) redirect("/");
	return (
		<>
			<h1>Sign in</h1>
			<Form action="/api/login">
				<label htmlFor="username">Username</label>
				<input name="username" id="username" />
				<br />
				<label htmlFor="password">Password</label>
				<input type="password" name="password" id="password" />
				<br />
				<input type="submit" />
			</Form>
			<Link href="/signup">Create an account</Link>
		</>
	);
};

export default Page;

// examples/sveltekit/username-and-password/src/routes/login/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";

    import type { ActionData } from './$types';

    export let form: ActionData;
</script>

<h1>Sign in</h1>
<form method="post" use:enhance>
	<label for="username">Username</label>
	<input name="username" id="username" /><br>
	<label for="password">Password</label>
	<input type="password" name="password" id="password" /><br>
	<input type="submit" />
</form>
{#if form?.message}
<p class="error">{form.message}</p>
{/if}
<a href="/signup">Create an account</a>
